
//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// 
//------------------------------------------------------------------------------

// Generated from: login.proto
// Note: requires additional types generated from: msgcode.proto
namespace PaoEntity
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginRegisterKey_Req")]
    public partial class LoginRegisterKey_Req : global::ProtoBuf.IExtensible
    {
      public LoginRegisterKey_Req() {}
      

    private PaoEntity.MsgCode _msgcode = PaoEntity.MsgCode.LG_RG_KEY_REQ;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msgcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(PaoEntity.MsgCode.LG_RG_KEY_REQ)]
    public PaoEntity.MsgCode msgcode
    {
      get { return _msgcode; }
      set { _msgcode = value; }
    }
    private string _deviceCode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"deviceCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string deviceCode
    {
      get { return _deviceCode; }
      set { _deviceCode = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginRegisterKey_Res")]
    public partial class LoginRegisterKey_Res : global::ProtoBuf.IExtensible
    {
      public LoginRegisterKey_Res() {}
      

    private PaoEntity.MsgCode _msgcode = PaoEntity.MsgCode.LG_RG_KEY_RES;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msgcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(PaoEntity.MsgCode.LG_RG_KEY_RES)]
    public PaoEntity.MsgCode msgcode
    {
      get { return _msgcode; }
      set { _msgcode = value; }
    }
    private int _code;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int code
    {
      get { return _code; }
      set { _code = value; }
    }
    private string _account;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _psw;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"psw", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string psw
    {
      get { return _psw; }
      set { _psw = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_LG_CTL_REGIST")]
    public partial class CMD_LG_CTL_REGIST : global::ProtoBuf.IExtensible
    {
      public CMD_LG_CTL_REGIST() {}
      

    private PaoEntity.MsgCode _msgcode = PaoEntity.MsgCode.LG_CTL_REGIST;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msgcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(PaoEntity.MsgCode.LG_CTL_REGIST)]
    public PaoEntity.MsgCode msgcode
    {
      get { return _msgcode; }
      set { _msgcode = value; }
    }
    private string _account;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _psw;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"psw", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string psw
    {
      get { return _psw; }
      set { _psw = value; }
    }
    private string _code;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string code
    {
      get { return _code; }
      set { _code = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_LG_LTC_REGIST")]
    public partial class CMD_LG_LTC_REGIST : global::ProtoBuf.IExtensible
    {
      public CMD_LG_LTC_REGIST() {}
      

    private PaoEntity.MsgCode _msgcode = PaoEntity.MsgCode.LG_LTC_REGIST;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msgcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(PaoEntity.MsgCode.LG_LTC_REGIST)]
    public PaoEntity.MsgCode msgcode
    {
      get { return _msgcode; }
      set { _msgcode = value; }
    }
    private int _retcode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_LG_CTL_MODIFYPSW")]
    public partial class CMD_LG_CTL_MODIFYPSW : global::ProtoBuf.IExtensible
    {
      public CMD_LG_CTL_MODIFYPSW() {}
      

    private PaoEntity.MsgCode _msgcode = PaoEntity.MsgCode.LG_CTL_MODIFYPSW;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msgcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(PaoEntity.MsgCode.LG_CTL_MODIFYPSW)]
    public PaoEntity.MsgCode msgcode
    {
      get { return _msgcode; }
      set { _msgcode = value; }
    }
    private string _newpsw;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"newpsw", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string newpsw
    {
      get { return _newpsw; }
      set { _newpsw = value; }
    }
    private string _account;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _oldpsw;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"oldpsw", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string oldpsw
    {
      get { return _oldpsw; }
      set { _oldpsw = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_LG_LTC_MODIFYPSW")]
    public partial class CMD_LG_LTC_MODIFYPSW : global::ProtoBuf.IExtensible
    {
      public CMD_LG_LTC_MODIFYPSW() {}
      

    private PaoEntity.MsgCode _msgcode = PaoEntity.MsgCode.LG_LTC_MODIFYPSW;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msgcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(PaoEntity.MsgCode.LG_LTC_MODIFYPSW)]
    public PaoEntity.MsgCode msgcode
    {
      get { return _msgcode; }
      set { _msgcode = value; }
    }
    private int _retcode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"retcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int retcode
    {
      get { return _retcode; }
      set { _retcode = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_LG_CTL_REGCODE")]
    public partial class CMD_LG_CTL_REGCODE : global::ProtoBuf.IExtensible
    {
      public CMD_LG_CTL_REGCODE() {}
      

    private PaoEntity.MsgCode _msgcode = PaoEntity.MsgCode.LG_CTL_REGCODE;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msgcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(PaoEntity.MsgCode.LG_CTL_REGCODE)]
    public PaoEntity.MsgCode msgcode
    {
      get { return _msgcode; }
      set { _msgcode = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_LG_LTC_REGCODE")]
    public partial class CMD_LG_LTC_REGCODE : global::ProtoBuf.IExtensible
    {
      public CMD_LG_LTC_REGCODE() {}
      

    private PaoEntity.MsgCode _msgcode = PaoEntity.MsgCode.LG_LTC_REGCODE;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msgcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(PaoEntity.MsgCode.LG_LTC_REGCODE)]
    public PaoEntity.MsgCode msgcode
    {
      get { return _msgcode; }
      set { _msgcode = value; }
    }
    private string _code;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string code
    {
      get { return _code; }
      set { _code = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_LG_CTL_LOGIN")]
    public partial class CMD_LG_CTL_LOGIN : global::ProtoBuf.IExtensible
    {
      public CMD_LG_CTL_LOGIN() {}
      

    private PaoEntity.MsgCode _mgscode = PaoEntity.MsgCode.LG_CTL_LOGIN;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mgscode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(PaoEntity.MsgCode.LG_CTL_LOGIN)]
    public PaoEntity.MsgCode mgscode
    {
      get { return _mgscode; }
      set { _mgscode = value; }
    }
    private string _account;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _DeviceCode;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"DeviceCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DeviceCode
    {
      get { return _DeviceCode; }
      set { _DeviceCode = value; }
    }
    private string _AppCode;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"AppCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string AppCode
    {
      get { return _AppCode; }
      set { _AppCode = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_LG_LTC_LOGIN")]
    public partial class CMD_LG_LTC_LOGIN : global::ProtoBuf.IExtensible
    {
      public CMD_LG_LTC_LOGIN() {}
      

    private PaoEntity.MsgCode _msgcode = PaoEntity.MsgCode.LG_LTC_LOGIN;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msgcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(PaoEntity.MsgCode.LG_LTC_LOGIN)]
    public PaoEntity.MsgCode msgcode
    {
      get { return _msgcode; }
      set { _msgcode = value; }
    }
    private int _result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }

    private int _BanTime = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"BanTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(default(int))]
    public int BanTime
    {
      get { return _BanTime; }
      set { _BanTime = value; }
    }

    private string _reason = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.Default)][global::System.ComponentModel.DefaultValue("")]
    public string reason
    {
      get { return _reason; }
      set { _reason = value; }
    }

    private string _Token = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Token", DataFormat = global::ProtoBuf.DataFormat.Default)][global::System.ComponentModel.DefaultValue("")]
    public string Token
    {
      get { return _Token; }
      set { _Token = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_LG_CTG_LOGIN")]
    public partial class CMD_LG_CTG_LOGIN : global::ProtoBuf.IExtensible
    {
      public CMD_LG_CTG_LOGIN() {}
      

    private PaoEntity.MsgCode _msgcode = PaoEntity.MsgCode.LG_CTG_LOGIN;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msgcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(PaoEntity.MsgCode.LG_CTG_LOGIN)]
    public PaoEntity.MsgCode msgcode
    {
      get { return _msgcode; }
      set { _msgcode = value; }
    }
    private string _Token;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Token
    {
      get { return _Token; }
      set { _Token = value; }
    }
    private string _DeviceID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"DeviceID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DeviceID
    {
      get { return _DeviceID; }
      set { _DeviceID = value; }
    }
    private string _PlatID;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"PlatID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PlatID
    {
      get { return _PlatID; }
      set { _PlatID = value; }
    }
    private string _ClientOS;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"ClientOS", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ClientOS
    {
      get { return _ClientOS; }
      set { _ClientOS = value; }
    }

    private bool _Reconnect = (bool)false;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Reconnect", DataFormat = global::ProtoBuf.DataFormat.Default)][global::System.ComponentModel.DefaultValue((bool)false)]
    public bool Reconnect
    {
      get { return _Reconnect; }
      set { _Reconnect = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerInfo")]
    public partial class ServerInfo : global::ProtoBuf.IExtensible
    {
      public ServerInfo() {}
      
    private int _ServerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ServerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ServerId
    {
      get { return _ServerId; }
      set { _ServerId = value; }
    }
    private int _Type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private int _Zone;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Zone", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Zone
    {
      get { return _Zone; }
      set { _Zone = value; }
    }
    private string _Name;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private string _GateIP;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"GateIP", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string GateIP
    {
      get { return _GateIP; }
      set { _GateIP = value; }
    }
    private int _GatePort;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"GatePort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int GatePort
    {
      get { return _GatePort; }
      set { _GatePort = value; }
    }
    private int _State;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"State", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int State
    {
      get { return _State; }
      set { _State = value; }
    }

    private string _Tips = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"Tips", DataFormat = global::ProtoBuf.DataFormat.Default)][global::System.ComponentModel.DefaultValue("")]
    public string Tips
    {
      get { return _Tips; }
      set { _Tips = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PageInfo")]
    public partial class PageInfo : global::ProtoBuf.IExtensible
    {
      public PageInfo() {}
      
    private string _PageName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"PageName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PageName
    {
      get { return _PageName; }
      set { _PageName = value; }
    }
    private int _SortId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"SortId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SortId
    {
      get { return _SortId; }
      set { _SortId = value; }
    }
    private readonly global::System.Collections.Generic.List<PaoEntity.ServerInfo> _ServerS = new global::System.Collections.Generic.List<PaoEntity.ServerInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"ServerS", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PaoEntity.ServerInfo> ServerS
    {
      get { return _ServerS; }
    }
  
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_LG_LTC_SERVERLIST")]
    public partial class CMD_LG_LTC_SERVERLIST : global::ProtoBuf.IExtensible
    {
      public CMD_LG_LTC_SERVERLIST() {}
      

    private PaoEntity.MsgCode _msgcode = PaoEntity.MsgCode.LG_LTC_SERVERLIST;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msgcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(PaoEntity.MsgCode.LG_LTC_SERVERLIST)]
    public PaoEntity.MsgCode msgcode
    {
      get { return _msgcode; }
      set { _msgcode = value; }
    }
    private readonly global::System.Collections.Generic.List<PaoEntity.PageInfo> _Pages = new global::System.Collections.Generic.List<PaoEntity.PageInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"Pages", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PaoEntity.PageInfo> Pages
    {
      get { return _Pages; }
    }
  
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_LG_CTL_SERVERLIST")]
    public partial class CMD_LG_CTL_SERVERLIST : global::ProtoBuf.IExtensible
    {
      public CMD_LG_CTL_SERVERLIST() {}
      

    private PaoEntity.MsgCode _msgcode = PaoEntity.MsgCode.LG_CTL_SERVERLIST;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msgcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(PaoEntity.MsgCode.LG_CTL_SERVERLIST)]
    public PaoEntity.MsgCode msgcode
    {
      get { return _msgcode; }
      set { _msgcode = value; }
    }

    private string _Account = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Account", DataFormat = global::ProtoBuf.DataFormat.Default)][global::System.ComponentModel.DefaultValue("")]
    public string Account
    {
      get { return _Account; }
      set { _Account = value; }
    }

    private string _PackName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"PackName", DataFormat = global::ProtoBuf.DataFormat.Default)][global::System.ComponentModel.DefaultValue("")]
    public string PackName
    {
      get { return _PackName; }
      set { _PackName = value; }
    }

    private string _Version = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Version", DataFormat = global::ProtoBuf.DataFormat.Default)][global::System.ComponentModel.DefaultValue("")]
    public string Version
    {
      get { return _Version; }
      set { _Version = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_LG_GTC_CLOSECONNECTION")]
    public partial class CMD_LG_GTC_CLOSECONNECTION : global::ProtoBuf.IExtensible
    {
      public CMD_LG_GTC_CLOSECONNECTION() {}
      

    private PaoEntity.MsgCode _msgcode = PaoEntity.MsgCode.LG_GTC_CLOSECONNECTION;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msgcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(PaoEntity.MsgCode.LG_GTC_CLOSECONNECTION)]
    public PaoEntity.MsgCode msgcode
    {
      get { return _msgcode; }
      set { _msgcode = value; }
    }
    private PaoEntity.CMD_LG_GTC_CLOSECONNECTION.CloseReason _Reason;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public PaoEntity.CMD_LG_GTC_CLOSECONNECTION.CloseReason Reason
    {
      get { return _Reason; }
      set { _Reason = value; }
    }
    public enum CloseReason
    {
      ForceLogin = 1,
    Expired = 2,
    IllegalOpration = 3,
    ServerShutDown = 4,
    CatastrophicError = 5
    }
  
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_LG_LTC_LATESTLOGININFO")]
    public partial class CMD_LG_LTC_LATESTLOGININFO : global::ProtoBuf.IExtensible
    {
      public CMD_LG_LTC_LATESTLOGININFO() {}
      

    private PaoEntity.MsgCode _msgcode = PaoEntity.MsgCode.LG_LTC_LATESTLOGININFO;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msgcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(PaoEntity.MsgCode.LG_LTC_LATESTLOGININFO)]
    public PaoEntity.MsgCode msgcode
    {
      get { return _msgcode; }
      set { _msgcode = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _ServerList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"ServerList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> ServerList
    {
      get { return _ServerList; }
    }
  
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_LG_GTC_LOGIN")]
    public partial class CMD_LG_GTC_LOGIN : global::ProtoBuf.IExtensible
    {
      public CMD_LG_GTC_LOGIN() {}
      

    private PaoEntity.MsgCode _msgcode = PaoEntity.MsgCode.LG_GTC_LOGIN;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msgcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(PaoEntity.MsgCode.LG_GTC_LOGIN)]
    public PaoEntity.MsgCode msgcode
    {
      get { return _msgcode; }
      set { _msgcode = value; }
    }
    private int _ReturnCode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ReturnCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ReturnCode
    {
      get { return _ReturnCode; }
      set { _ReturnCode = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_LG_LTC_NOTICE")]
    public partial class CMD_LG_LTC_NOTICE : global::ProtoBuf.IExtensible
    {
      public CMD_LG_LTC_NOTICE() {}
      

    private PaoEntity.MsgCode _msgcode = PaoEntity.MsgCode.LG_LTC_NOTICE;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msgcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(PaoEntity.MsgCode.LG_LTC_NOTICE)]
    public PaoEntity.MsgCode msgcode
    {
      get { return _msgcode; }
      set { _msgcode = value; }
    }
    private string _Tittle;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Tittle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Tittle
    {
      get { return _Tittle; }
      set { _Tittle = value; }
    }
    private string _Content;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Content
    {
      get { return _Content; }
      set { _Content = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_LG_CTG_KEEPALIVE")]
    public partial class CMD_LG_CTG_KEEPALIVE : global::ProtoBuf.IExtensible
    {
      public CMD_LG_CTG_KEEPALIVE() {}
      

    private PaoEntity.MsgCode _msgcode = PaoEntity.MsgCode.LG_CTG_KEEPALIVE;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msgcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(PaoEntity.MsgCode.LG_CTG_KEEPALIVE)]
    public PaoEntity.MsgCode msgcode
    {
      get { return _msgcode; }
      set { _msgcode = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_LG_GTC_KEEPALIVE")]
    public partial class CMD_LG_GTC_KEEPALIVE : global::ProtoBuf.IExtensible
    {
      public CMD_LG_GTC_KEEPALIVE() {}
      

    private PaoEntity.MsgCode _msgcode = PaoEntity.MsgCode.LG_GTC_KEEPALIVE;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msgcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(PaoEntity.MsgCode.LG_GTC_KEEPALIVE)]
    public PaoEntity.MsgCode msgcode
    {
      get { return _msgcode; }
      set { _msgcode = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
}
//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// 
//------------------------------------------------------------------------------

// Generated from: msgcode.proto
namespace PaoEntity
{
    public enum MsgCode
    {
      TEST_REQUEST = 536875008,
    TEST_RESPONSE = 268439552,
    SERVER_GTL_VALIDATE = 805306378,
    SERVER_LTG_VALIDATE = 10,
    SERVER_GTS_ENTERGAME = 536870913,
    SERVER_GTS_LEAVEGAME = 536870914,
    SERVER_STG_CLOSESESSION = 11,
    SERVER_STG_REPORT = 2,
    SERVER_STG_CLIENTLOGINED = 3,
    SERVER_GTL_CLIENTLOGINED = 805306369,
    SERVER_GTL_REGIST = 805306368,
    SERVER_GTL_GAMESTATUS = 805306370,
    SERVER_BTG_REPORT = 4,
    LG_GTC_CLOSECONNECTION = 268435456,
    LG_RG_KEY_REQ = 805310465,
    LG_RG_KEY_RES = 268439553,
    LG_CTL_REGIST = 805310466,
    LG_LTC_REGIST = 268439554,
    LG_CTL_MODIFYPSW = 805310467,
    LG_LTC_MODIFYPSW = 268439555,
    LG_CTL_REGCODE = 805310468,
    LG_LTC_REGCODE = 268439556,
    LG_CTL_LOGIN = 805310480,
    LG_LTC_LOGIN = 268439568,
    LG_LTC_SERVERLIST = 268439557,
    LG_CTL_SERVERLIST = 805310469,
    LG_LTC_LATESTLOGININFO = 268439558,
    LG_CTG_LOGIN = 12,
    LG_GTC_LOGIN = 268435468,
    LG_LTC_NOTICE = 268435469,
    LG_CTG_KEEPALIVE = 14,
    LG_GTC_KEEPALIVE = 268435470
    }
  
}
//------------------------------------------------------------------------------
// 
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// 
//------------------------------------------------------------------------------

// Generated from: syscoop.proto
// Note: requires additional types generated from: msgcode.proto
namespace PaoEntity
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_SERVER_GTL_VALIDATE")]
    public partial class CMD_SERVER_GTL_VALIDATE : global::ProtoBuf.IExtensible
    {
      public CMD_SERVER_GTL_VALIDATE() {}
      

    private PaoEntity.MsgCode _msgcode = PaoEntity.MsgCode.SERVER_GTL_VALIDATE;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msgcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(PaoEntity.MsgCode.SERVER_GTL_VALIDATE)]
    public PaoEntity.MsgCode msgcode
    {
      get { return _msgcode; }
      set { _msgcode = value; }
    }
    private string _Token;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Token
    {
      get { return _Token; }
      set { _Token = value; }
    }
    private long _NetHandle;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"NetHandle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long NetHandle
    {
      get { return _NetHandle; }
      set { _NetHandle = value; }
    }
    private int _ServerID;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"ServerID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ServerID
    {
      get { return _ServerID; }
      set { _ServerID = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_SERVER_LTG_VALIDATE")]
    public partial class CMD_SERVER_LTG_VALIDATE : global::ProtoBuf.IExtensible
    {
      public CMD_SERVER_LTG_VALIDATE() {}
      

    private PaoEntity.MsgCode _msgcode = PaoEntity.MsgCode.SERVER_LTG_VALIDATE;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msgcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(PaoEntity.MsgCode.SERVER_LTG_VALIDATE)]
    public PaoEntity.MsgCode msgcode
    {
      get { return _msgcode; }
      set { _msgcode = value; }
    }
    private PaoEntity.CMD_SERVER_LTG_VALIDATE.ValidateResult _Result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public PaoEntity.CMD_SERVER_LTG_VALIDATE.ValidateResult Result
    {
      get { return _Result; }
      set { _Result = value; }
    }
    private string _Token;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Token
    {
      get { return _Token; }
      set { _Token = value; }
    }
    private string _UserID;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"UserID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string UserID
    {
      get { return _UserID; }
      set { _UserID = value; }
    }
    private long _NetHandle;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"NetHandle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long NetHandle
    {
      get { return _NetHandle; }
      set { _NetHandle = value; }
    }
    public enum ValidateResult
    {
      Success = 1,
    Expired = 2,
    NontFound = 3
    }
  
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_SERVER_GTS_ENTERGAME")]
    public partial class CMD_SERVER_GTS_ENTERGAME : global::ProtoBuf.IExtensible
    {
      public CMD_SERVER_GTS_ENTERGAME() {}
      

    private PaoEntity.MsgCode _msgcode = PaoEntity.MsgCode.SERVER_GTS_ENTERGAME;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msgcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(PaoEntity.MsgCode.SERVER_GTS_ENTERGAME)]
    public PaoEntity.MsgCode msgcode
    {
      get { return _msgcode; }
      set { _msgcode = value; }
    }
    private string _IP;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"IP", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string IP
    {
      get { return _IP; }
      set { _IP = value; }
    }
    private int _Port;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Port
    {
      get { return _Port; }
      set { _Port = value; }
    }
    private string _UserID;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"UserID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string UserID
    {
      get { return _UserID; }
      set { _UserID = value; }
    }
    private string _DevID;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"DevID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string DevID
    {
      get { return _DevID; }
      set { _DevID = value; }
    }
    private string _PlatID;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"PlatID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string PlatID
    {
      get { return _PlatID; }
      set { _PlatID = value; }
    }
    private string _ClientVersion;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"ClientVersion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ClientVersion
    {
      get { return _ClientVersion; }
      set { _ClientVersion = value; }
    }

    private bool _Reconnect = (bool)false;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"Reconnect", DataFormat = global::ProtoBuf.DataFormat.Default)][global::System.ComponentModel.DefaultValue((bool)false)]
    public bool Reconnect
    {
      get { return _Reconnect; }
      set { _Reconnect = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_SERVER_GTS_LEAVEGAME")]
    public partial class CMD_SERVER_GTS_LEAVEGAME : global::ProtoBuf.IExtensible
    {
      public CMD_SERVER_GTS_LEAVEGAME() {}
      

    private PaoEntity.MsgCode _msgcode = PaoEntity.MsgCode.SERVER_GTS_LEAVEGAME;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msgcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(PaoEntity.MsgCode.SERVER_GTS_LEAVEGAME)]
    public PaoEntity.MsgCode msgcode
    {
      get { return _msgcode; }
      set { _msgcode = value; }
    }
    private string _UserID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"UserID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string UserID
    {
      get { return _UserID; }
      set { _UserID = value; }
    }
    private int _Reason;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Reason
    {
      get { return _Reason; }
      set { _Reason = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_SERVER_STG_CLOSESESSION")]
    public partial class CMD_SERVER_STG_CLOSESESSION : global::ProtoBuf.IExtensible
    {
      public CMD_SERVER_STG_CLOSESESSION() {}
      

    private PaoEntity.MsgCode _msgcode = PaoEntity.MsgCode.SERVER_STG_CLOSESESSION;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msgcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(PaoEntity.MsgCode.SERVER_STG_CLOSESESSION)]
    public PaoEntity.MsgCode msgcode
    {
      get { return _msgcode; }
      set { _msgcode = value; }
    }
    private long _NetHandle;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"NetHandle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long NetHandle
    {
      get { return _NetHandle; }
      set { _NetHandle = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_SERVER_STG_REPORT")]
    public partial class CMD_SERVER_STG_REPORT : global::ProtoBuf.IExtensible
    {
      public CMD_SERVER_STG_REPORT() {}
      

    private PaoEntity.MsgCode _msgcode = PaoEntity.MsgCode.SERVER_STG_REPORT;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msgcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(PaoEntity.MsgCode.SERVER_STG_REPORT)]
    public PaoEntity.MsgCode msgcode
    {
      get { return _msgcode; }
      set { _msgcode = value; }
    }
    private int _ServerID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ServerID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ServerID
    {
      get { return _ServerID; }
      set { _ServerID = value; }
    }
    private string _ServerType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ServerType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ServerType
    {
      get { return _ServerType; }
      set { _ServerType = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_SERVER_GTL_REGIST")]
    public partial class CMD_SERVER_GTL_REGIST : global::ProtoBuf.IExtensible
    {
      public CMD_SERVER_GTL_REGIST() {}
      

    private PaoEntity.MsgCode _msgcode = PaoEntity.MsgCode.SERVER_GTL_REGIST;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msgcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(PaoEntity.MsgCode.SERVER_GTL_REGIST)]
    public PaoEntity.MsgCode msgcode
    {
      get { return _msgcode; }
      set { _msgcode = value; }
    }
    private int _ServerID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ServerID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ServerID
    {
      get { return _ServerID; }
      set { _ServerID = value; }
    }
    private bool _GameServerOpened;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"GameServerOpened", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool GameServerOpened
    {
      get { return _GameServerOpened; }
      set { _GameServerOpened = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_SERVER_GTL_GAMESTATUS")]
    public partial class CMD_SERVER_GTL_GAMESTATUS : global::ProtoBuf.IExtensible
    {
      public CMD_SERVER_GTL_GAMESTATUS() {}
      

    private PaoEntity.MsgCode _msgcode = PaoEntity.MsgCode.SERVER_GTL_GAMESTATUS;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msgcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(PaoEntity.MsgCode.SERVER_GTL_GAMESTATUS)]
    public PaoEntity.MsgCode msgcode
    {
      get { return _msgcode; }
      set { _msgcode = value; }
    }
    private int _ServerID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ServerID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ServerID
    {
      get { return _ServerID; }
      set { _ServerID = value; }
    }
    private string _ServerType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ServerType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ServerType
    {
      get { return _ServerType; }
      set { _ServerType = value; }
    }

    private bool _GameServerOpened = (bool)false;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"GameServerOpened", DataFormat = global::ProtoBuf.DataFormat.Default)][global::System.ComponentModel.DefaultValue((bool)false)]
    public bool GameServerOpened
    {
      get { return _GameServerOpened; }
      set { _GameServerOpened = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CMD_SERVER_BTG_REPORT")]
    public partial class CMD_SERVER_BTG_REPORT : global::ProtoBuf.IExtensible
    {
      public CMD_SERVER_BTG_REPORT() {}
      

    private PaoEntity.MsgCode _msgcode = PaoEntity.MsgCode.SERVER_BTG_REPORT;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msgcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)][global::System.ComponentModel.DefaultValue(PaoEntity.MsgCode.SERVER_BTG_REPORT)]
    public PaoEntity.MsgCode msgcode
    {
      get { return _msgcode; }
      set { _msgcode = value; }
    }
    private int _Flag;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Flag
    {
      get { return _Flag; }
      set { _Flag = value; }
    }
      private global::ProtoBuf.IExtension extensionObject;
      global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }
  
    public enum LeaveReason
    {
      Normal = 1,
    Kick = 2,
    Replace = 3
    }
  
}