//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using Dos.ORM;

namespace Dos.Model
{
    
	/// <summary>
	/// 实体类character 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Table("p_character")]
	[Serializable]
	public partial class character : Entity 
	{
		#region Model
		private int _Index;
		private string _GUID;
		private string _Account;
		private int? _CreateServer;
		private DateTime? _CreateTime;
		private DateTime? _LeaveTime;
		private string _Icon;
		private string _Name;
		private int? _Level;
		private int? _Exp;
		private int? _Gender;
		private int? _MaxFight;
		private int? _MaxArenaRank;
		private int? _HaveChangeName;
		/// <summary>
		/// 
		/// </summary>
		public int Index
		{
			get{ return _Index; }
			set
			{
				this.OnPropertyValueChange(_.Index,_Index,value);
				this._Index=value;
			}
		}
		/// <summary>
		/// 角色Id
		/// </summary>
		public string GUID
		{
			get{ return _GUID; }
			set
			{
				this.OnPropertyValueChange(_.GUID,_GUID,value);
				this._GUID=value;
			}
		}
		/// <summary>
		/// 用户账号
		/// </summary>
		public string Account
		{
			get{ return _Account; }
			set
			{
				this.OnPropertyValueChange(_.Account,_Account,value);
				this._Account=value;
			}
		}
		/// <summary>
		/// 创建游戏服
		/// </summary>
		public int? CreateServer
		{
			get{ return _CreateServer; }
			set
			{
				this.OnPropertyValueChange(_.CreateServer,_CreateServer,value);
				this._CreateServer=value;
			}
		}
		/// <summary>
		/// 账号创建时间
		/// </summary>
		public DateTime? CreateTime
		{
			get{ return _CreateTime; }
			set
			{
				this.OnPropertyValueChange(_.CreateTime,_CreateTime,value);
				this._CreateTime=value;
			}
		}
		/// <summary>
		/// 离线时间（上次登录时间）
		/// </summary>
		public DateTime? LeaveTime
		{
			get{ return _LeaveTime; }
			set
			{
				this.OnPropertyValueChange(_.LeaveTime,_LeaveTime,value);
				this._LeaveTime=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string Icon
		{
			get{ return _Icon; }
			set
			{
				this.OnPropertyValueChange(_.Icon,_Icon,value);
				this._Icon=value;
			}
		}
		/// <summary>
		/// 角色名字
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 等级
		/// </summary>
		public int? Level
		{
			get{ return _Level; }
			set
			{
				this.OnPropertyValueChange(_.Level,_Level,value);
				this._Level=value;
			}
		}
		/// <summary>
		/// 经验
		/// </summary>
		public int? Exp
		{
			get{ return _Exp; }
			set
			{
				this.OnPropertyValueChange(_.Exp,_Exp,value);
				this._Exp=value;
			}
		}
		/// <summary>
		/// _0：女 1：男
		/// </summary>
		public int? Gender
		{
			get{ return _Gender; }
			set
			{
				this.OnPropertyValueChange(_.Gender,_Gender,value);
				this._Gender=value;
			}
		}
		/// <summary>
		/// 最大战力
		/// </summary>
		public int? MaxFight
		{
			get{ return _MaxFight; }
			set
			{
				this.OnPropertyValueChange(_.MaxFight,_MaxFight,value);
				this._MaxFight=value;
			}
		}
		/// <summary>
		/// 历史最大竞技场排名
		/// </summary>
		public int? MaxArenaRank
		{
			get{ return _MaxArenaRank; }
			set
			{
				this.OnPropertyValueChange(_.MaxArenaRank,_MaxArenaRank,value);
				this._MaxArenaRank=value;
			}
		}
		/// <summary>
		/// 是否改过名 0没有，1有
		/// </summary>
		public int? HaveChangeName
		{
			get{ return _HaveChangeName; }
			set
			{
				this.OnPropertyValueChange(_.HaveChangeName,_HaveChangeName,value);
				this._HaveChangeName=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Index};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Index,
				_.GUID,
				_.Account,
				_.CreateServer,
				_.CreateTime,
				_.LeaveTime,
				_.Icon,
				_.Name,
				_.Level,
				_.Exp,
				_.Gender,
				_.MaxFight,
				_.MaxArenaRank,
				_.HaveChangeName};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Index,
				this._GUID,
				this._Account,
				this._CreateServer,
				this._CreateTime,
				this._LeaveTime,
				this._Icon,
				this._Name,
				this._Level,
				this._Exp,
				this._Gender,
				this._MaxFight,
				this._MaxArenaRank,
				this._HaveChangeName};
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","p_character");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Index = new Field("Index","p_character","Index");
			/// <summary>
			/// 角色Id
			/// </summary>
			public readonly static Field GUID = new Field("GUID","p_character","角色Id");
			/// <summary>
			/// 用户账号
			/// </summary>
			public readonly static Field Account = new Field("Account","p_character","用户账号");
			/// <summary>
			/// 创建游戏服
			/// </summary>
			public readonly static Field CreateServer = new Field("CreateServer","p_character","创建游戏服");
			/// <summary>
			/// 账号创建时间
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime","p_character","账号创建时间");
			/// <summary>
			/// 离线时间（上次登录时间）
			/// </summary>
			public readonly static Field LeaveTime = new Field("LeaveTime","p_character","离线时间（上次登录时间）");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Icon = new Field("Icon","p_character","Icon");
			/// <summary>
			/// 角色名字
			/// </summary>
			public readonly static Field Name = new Field("Name","p_character","角色名字");
			/// <summary>
			/// 等级
			/// </summary>
			public readonly static Field Level = new Field("Level","p_character","等级");
			/// <summary>
			/// 经验
			/// </summary>
			public readonly static Field Exp = new Field("Exp","p_character","经验");
			/// <summary>
			/// _0：女 1：男
			/// </summary>
			public readonly static Field Gender = new Field("Gender","p_character","_0：女 1：男");
			/// <summary>
			/// 最大战力
			/// </summary>
			public readonly static Field MaxFight = new Field("MaxFight","p_character","最大战力");
			/// <summary>
			/// 历史最大竞技场排名
			/// </summary>
			public readonly static Field MaxArenaRank = new Field("MaxArenaRank","p_character","历史最大竞技场排名");
			/// <summary>
			/// 是否改过名 0没有，1有
			/// </summary>
			public readonly static Field HaveChangeName = new Field("HaveChangeName","p_character","是否改过名 0没有，1有");
		}
		#endregion


	}
}

