//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace Dos.Model
{
    /// <summary>
    /// 实体类p_arena。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("p_arena")]
    [Serializable]
    public partial class p_arena : Entity
    {
        #region Model
		private int _Rank;
		private int? _Type;
		private string _GUID;
		private string _Name;
		private int? _ChallengeTimes;
		private DateTime? _LastChallengeTime;
		private int? _MaxRank;
		private int? _WonTimes;
		private int? _LostTimes;
		private int? _CommanderFormType;
		private string _SoldierList;
		private string _SkillList;
		private int? _BuyChallengeCount;
		private int? _ArenaCoin;
		private int? _LogSign;
		private DateTime? _LastBuyChallengeCountTime;
		private string _SkillGrades;

		/// <summary>
		/// 
		/// </summary>
		[Field("Rank")]
		public int Rank
		{
			get{ return _Rank; }
			set
			{
				this.OnPropertyValueChange("Rank");
				this._Rank = value;
			}
		}
		/// <summary>
		/// _0:机器人，1:玩家
		/// </summary>
		[Field("Type")]
		public int? Type
		{
			get{ return _Type; }
			set
			{
				this.OnPropertyValueChange("Type");
				this._Type = value;
			}
		}
		/// <summary>
		/// 实例Id
		/// </summary>
		[Field("GUID")]
		public string GUID
		{
			get{ return _GUID; }
			set
			{
				this.OnPropertyValueChange("GUID");
				this._GUID = value;
			}
		}
		/// <summary>
		/// 参赛者名字
		/// </summary>
		[Field("Name")]
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange("Name");
				this._Name = value;
			}
		}
		/// <summary>
		/// 挑战次数
		/// </summary>
		[Field("ChallengeTimes")]
		public int? ChallengeTimes
		{
			get{ return _ChallengeTimes; }
			set
			{
				this.OnPropertyValueChange("ChallengeTimes");
				this._ChallengeTimes = value;
			}
		}
		/// <summary>
		/// 上次挑战时间
		/// </summary>
		[Field("LastChallengeTime")]
		public DateTime? LastChallengeTime
		{
			get{ return _LastChallengeTime; }
			set
			{
				this.OnPropertyValueChange("LastChallengeTime");
				this._LastChallengeTime = value;
			}
		}
		/// <summary>
		/// 最大排名
		/// </summary>
		[Field("MaxRank")]
		public int? MaxRank
		{
			get{ return _MaxRank; }
			set
			{
				this.OnPropertyValueChange("MaxRank");
				this._MaxRank = value;
			}
		}
		/// <summary>
		/// 胜场次数
		/// </summary>
		[Field("WonTimes")]
		public int? WonTimes
		{
			get{ return _WonTimes; }
			set
			{
				this.OnPropertyValueChange("WonTimes");
				this._WonTimes = value;
			}
		}
		/// <summary>
		/// 败场次数
		/// </summary>
		[Field("LostTimes")]
		public int? LostTimes
		{
			get{ return _LostTimes; }
			set
			{
				this.OnPropertyValueChange("LostTimes");
				this._LostTimes = value;
			}
		}
		/// <summary>
		/// 指挥官初始形态
		/// </summary>
		[Field("CommanderFormType")]
		public int? CommanderFormType
		{
			get{ return _CommanderFormType; }
			set
			{
				this.OnPropertyValueChange("CommanderFormType");
				this._CommanderFormType = value;
			}
		}
		/// <summary>
		/// 参战兵种GUID列表，逗号分隔
		/// </summary>
		[Field("SoldierList")]
		public string SoldierList
		{
			get{ return _SoldierList; }
			set
			{
				this.OnPropertyValueChange("SoldierList");
				this._SoldierList = value;
			}
		}
		/// <summary>
		/// 科技技能模板ID列表，逗号隔开
		/// </summary>
		[Field("SkillList")]
		public string SkillList
		{
			get{ return _SkillList; }
			set
			{
				this.OnPropertyValueChange("SkillList");
				this._SkillList = value;
			}
		}
		/// <summary>
		/// 剩余可购买挑战次数
		/// </summary>
		[Field("BuyChallengeCount")]
		public int? BuyChallengeCount
		{
			get{ return _BuyChallengeCount; }
			set
			{
				this.OnPropertyValueChange("BuyChallengeCount");
				this._BuyChallengeCount = value;
			}
		}
		/// <summary>
		/// 竞技场兑换币
		/// </summary>
		[Field("ArenaCoin")]
		public int? ArenaCoin
		{
			get{ return _ArenaCoin; }
			set
			{
				this.OnPropertyValueChange("ArenaCoin");
				this._ArenaCoin = value;
			}
		}
		/// <summary>
		/// _0：没有新纪录 1：有新记录
		/// </summary>
		[Field("LogSign")]
		public int? LogSign
		{
			get{ return _LogSign; }
			set
			{
				this.OnPropertyValueChange("LogSign");
				this._LogSign = value;
			}
		}
		/// <summary>
		/// 最近一次购买时间
		/// </summary>
		[Field("LastBuyChallengeCountTime")]
		public DateTime? LastBuyChallengeCountTime
		{
			get{ return _LastBuyChallengeCountTime; }
			set
			{
				this.OnPropertyValueChange("LastBuyChallengeCountTime");
				this._LastBuyChallengeCountTime = value;
			}
		}
		/// <summary>
		/// 科技品阶信息
		/// </summary>
		[Field("SkillGrades")]
		public string SkillGrades
		{
			get{ return _SkillGrades; }
			set
			{
				this.OnPropertyValueChange("SkillGrades");
				this._SkillGrades = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.Rank,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.Rank,
				_.Type,
				_.GUID,
				_.Name,
				_.ChallengeTimes,
				_.LastChallengeTime,
				_.MaxRank,
				_.WonTimes,
				_.LostTimes,
				_.CommanderFormType,
				_.SoldierList,
				_.SkillList,
				_.BuyChallengeCount,
				_.ArenaCoin,
				_.LogSign,
				_.LastBuyChallengeCountTime,
				_.SkillGrades,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._Rank,
				this._Type,
				this._GUID,
				this._Name,
				this._ChallengeTimes,
				this._LastChallengeTime,
				this._MaxRank,
				this._WonTimes,
				this._LostTimes,
				this._CommanderFormType,
				this._SoldierList,
				this._SkillList,
				this._BuyChallengeCount,
				this._ArenaCoin,
				this._LogSign,
				this._LastBuyChallengeCountTime,
				this._SkillGrades,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "p_arena");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Rank = new Field("Rank", "p_arena", "");
            /// <summary>
			/// _0:机器人，1:玩家
			/// </summary>
			public readonly static Field Type = new Field("Type", "p_arena", "_0:机器人，1:玩家");
            /// <summary>
			/// 实例Id
			/// </summary>
			public readonly static Field GUID = new Field("GUID", "p_arena", "实例Id");
            /// <summary>
			/// 参赛者名字
			/// </summary>
			public readonly static Field Name = new Field("Name", "p_arena", "参赛者名字");
            /// <summary>
			/// 挑战次数
			/// </summary>
			public readonly static Field ChallengeTimes = new Field("ChallengeTimes", "p_arena", "挑战次数");
            /// <summary>
			/// 上次挑战时间
			/// </summary>
			public readonly static Field LastChallengeTime = new Field("LastChallengeTime", "p_arena", "上次挑战时间");
            /// <summary>
			/// 最大排名
			/// </summary>
			public readonly static Field MaxRank = new Field("MaxRank", "p_arena", "最大排名");
            /// <summary>
			/// 胜场次数
			/// </summary>
			public readonly static Field WonTimes = new Field("WonTimes", "p_arena", "胜场次数");
            /// <summary>
			/// 败场次数
			/// </summary>
			public readonly static Field LostTimes = new Field("LostTimes", "p_arena", "败场次数");
            /// <summary>
			/// 指挥官初始形态
			/// </summary>
			public readonly static Field CommanderFormType = new Field("CommanderFormType", "p_arena", "指挥官初始形态");
            /// <summary>
			/// 参战兵种GUID列表，逗号分隔
			/// </summary>
			public readonly static Field SoldierList = new Field("SoldierList", "p_arena", "参战兵种GUID列表，逗号分隔");
            /// <summary>
			/// 科技技能模板ID列表，逗号隔开
			/// </summary>
			public readonly static Field SkillList = new Field("SkillList", "p_arena", "科技技能模板ID列表，逗号隔开");
            /// <summary>
			/// 剩余可购买挑战次数
			/// </summary>
			public readonly static Field BuyChallengeCount = new Field("BuyChallengeCount", "p_arena", "剩余可购买挑战次数");
            /// <summary>
			/// 竞技场兑换币
			/// </summary>
			public readonly static Field ArenaCoin = new Field("ArenaCoin", "p_arena", "竞技场兑换币");
            /// <summary>
			/// _0：没有新纪录 1：有新记录
			/// </summary>
			public readonly static Field LogSign = new Field("LogSign", "p_arena", "_0：没有新纪录 1：有新记录");
            /// <summary>
			/// 最近一次购买时间
			/// </summary>
			public readonly static Field LastBuyChallengeCountTime = new Field("LastBuyChallengeCountTime", "p_arena", "最近一次购买时间");
            /// <summary>
			/// 科技品阶信息
			/// </summary>
			public readonly static Field SkillGrades = new Field("SkillGrades", "p_arena", "科技品阶信息");
        }
        #endregion
	}
}