//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;
using Dos.ORM;

namespace Dos.Model
{
    /// <summary>
    /// 实体类xyaccount。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("xyaccount")]
    [Serializable]
	[DataContract]
    public partial class xyaccount : Entity
    {
        #region Model
		private int _index;
		private string _account;

		/// <summary>
		/// 
		/// </summary>
		[Field("index")]
		[DataMember]
		public int index
		{
			get{ return _index; }
			set
			{
				this.OnPropertyValueChange("index");
				this._index = value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		[Field("account")]
		[DataMember]
		public string account
		{
			get{ return _account; }
			set
			{
				this.OnPropertyValueChange("account");
				this._account = value;
			}
		}
		#endregion

		#region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
				_.index,
			};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
				_.index,
				_.account,
			};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
				this._index,
				this._account,
			};
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

		#region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*", "xyaccount");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field index = new Field("index", "xyaccount", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field account = new Field("account", "xyaccount", "");
        }
        #endregion
	}
}